---
- name: test play
  hosts: localhost
  tasks:
    - name: add delegation host
      add_host:
        name: dev
        ansible_host: 192.168.1.33
        ansible_user: pmurali
    - name: echo hello
      command: echo "Hello from {{ inventory_hostname }}"
      delegate_to: dev
      register: output

    - debug:
        msg: "{{ output.stdout }}"
